### ISSUE TITLE
groupNodes and elemens mismatch length

### ISSUE THREAD

**Issue by TamimiGitHub** [dai-shi/excalidraw-animate#43]
I am attempting to animate an excalidraw diagram however getting the following error in the console logs

```
animate.ts:661 Uncaught (in promise) Error: element length mismatch
    at animateSvg (animate.ts:661:1)
    at useLoadSvg.ts:74:1
    at async Promise.all (:3000/index 0)
    at async useLoadSvg.ts:65:1
    at async useLoadSvg.ts:98:1
```
Upon further investigating, I realized that `animate.ts` throws an error for this. 

Here is a link to my exaclidraw diagram https://excalidraw.com/#json=-9jiwl8sky-JV5f6tys9A,u1j_Dzj5lOyKBj25-MEpMA

**Comment by dai-shi** [comment]
Thanks for reporting.

I think we should update excalidraw package and if the problem persists, fix it.

**Comment by dangehub** [comment]
2024-09-04 I meet the same problem

**Comment by dai-shi** [comment]
I wonder if @kei95 would be interested in it.

**Comment by kei95** [comment]
Hmm it doesn't look like that I can reproduce this with the given drawing from @TamimiGitHub. @dangehub is there any chance that you could provide us your drawing with the issue so that I can look into it?

<img width="1440" alt="Screenshot 2024-09-05 at 5 16 16 PM" src="https://github.com/user-attachments/assets/96262cb6-0f7a-4783-a174-95d9afc05eca">

**Comment by dangehub** [comment]
> Hmm it doesn't look like that I can reproduce this with the given drawing from @TamimiGitHub. @dangehub is there any chance that you could provide us your drawing with the issue so that I can look into it?
> 
> <img alt="Screenshot 2024-09-05 at 5 16 16 PM" width="1440" src="https://private-user-images.githubusercontent.com/44686790/364686603-96262cb6-0f7a-4783-a174-95d9afc05eca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MjUzMTIsIm5iZiI6MTcyNTUyNTAxMiwicGF0aCI6Ii80NDY4Njc5MC8zNjQ2ODY2MDMtOTYyNjJjYjYtMGY3YS00NzgzLWExNzQtOTVkOWFmYzA1ZWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA4MzAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3Yzk3YzZhMmY1YzIxY2M0ZWUxN2QyZjAzNDhiNzMxNTBmZTNjZjg2MjRmYWZhNTA2MmFjMWNiNGViNDBlNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JSIHUjSTJN3hPkr3O1qr2e8wCIiktKcCMkAi_pXI6aw">

Of course, I'd love to. I used obsidian's excalidraw plugin (2.4.1) to export it, and I can open it with the official excalidraw web.

[Drawing 2024-09-04 16.48.49.excalidraw.zip](https://github.com/user-attachments/files/16886340/Drawing.2024-09-04.16.48.49.excalidraw.zip)

**Comment by adoyle-h** [comment]
![Image](https://github.com/user-attachments/assets/bb782842-738c-4e99-9dc9-f2f33d0ab082)

Same problem

**Comment by rzayoruk** [comment]
same issue i have.

**Comment by dai-shi** [comment]
still help wanted.

@kei95 hasn't been active lately.
@kkoisland might have a chance to take a look.

**Comment by rzayoruk** [comment]
thanks for your interest.

**Comment by kkoisland** [comment]
Thank you for bringing up this issue! I found the problem.

The index-based matching problem is already known and discussed in [#110](https://github.com/dai-shi/excalidraw-animate/issues/110). The try-catch added in [#111](https://github.com/dai-shi/excalidraw-animate/pull/111) prevents infinite loading, but animation fails.

The root cause: when a diagram has an image element, `exportToSvg` does not generate a `<g>` node for it if the image file data is missing in files. This makes the element count and SVG node count different, and the error is thrown.

Note that this happens only with shared links. Local drawings saved to localStorage always have file data embedded, so the bug does not reproduce locally.

I'll fix this by filtering out image elements with missing file data before calling animateSvg. Will open a PR soon.
